#ifndef C_PROJECTS_FROM_NEWBIE_SHELL
#define C_PROJECTS_FROM_NEWBIE_SHELL

#define SIZE_BUFF_SHELL 4096
#define MAX_ARGS 64
static char BUFF_SHELL[SIZE_BUFF_SHELL];
static char LINE_BUFF[SIZE_BUFF_SHELL];

#endif
